name: CI/CD
on: 
  push:
    branches:
    - master
    paths:
    - "src/**"
    - "book.toml"
  workflow_dispatch:
    inputs:
      build-id:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.21'
    - run: mdbook build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      # if: ${{ github.ref == 'refs/heads/main' }}
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: Spalits00/JOL_book
        publish_branch: main
        publish_dir: ./book