name: CI/CD
on: 
  push:
  workflow_dispatch:
    inputs:
      build-id:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.21'
    - run: mdbook build
    - name: Build gh-pages to artifact
      uses: actions/upload-pages-artifact@v1
      # if: ${{ github.ref == 'refs/heads/main' }}
      with:
        path: ./book
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: Spalits00/JOL_book
        publish_branch: main